### ISSUE TITLE
Deprecated function: Function create_function() is deprecated in bueditor_sprite() 

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/bueditor#10]
With PHP 7.4. the module is giving:

```
Deprecated function: Function create_function() is deprecated in bueditor_sprite() (line 13 of /home/in/public_html/modules/bueditor/admin/bueditor.sprite.inc).
```

**Comment by findlabnet** [comment]
Same for PHP 7.3, below is my quick fix:
<pre>
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/<html>bueditor.sprite.inc (<b>Apr 27, 2015 11:51:00 AM</b>)</html>
+++ b/<html><b>Current File</b></html>
@@ -10,7 +10,9 @@
  */
 function bueditor_sprite($editor, $buttons = array()) {
   if (!empty($buttons)) {
-    uasort($buttons, create_function('$b1,$b2', 'return $b1->weight - $b2->weight;'));
+    uasort($buttons, function ($b1, $b2) {
+      return $b1->weight - $b2->weight;
+    });
     return bueditor_sprite_buttons($buttons, $editor->iconpath);
   }
   elseif (isset($editor->id) && $editor->id != '') {
###########################################################################
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/<html>bueditor.admin.inc (<b>Apr 27, 2015 11:51:00 AM</b>)</html>
+++ b/<html><b>Current File</b></html>
@@ -943,7 +943,9 @@
  */
 function bueditor_icons($path) {
   $icons = file_scan_directory($path, '/\.(png|gif|jpg)$/', array('recurse' => FALSE, 'key' => 'filename'));
-  array_walk($icons, create_function('&$value', '$value = 1;'));
+  array_walk($icons, function(&$value) {
+    $value = 1;
+  });
   return $icons;
 }

**Comment by herbdool** [comment]
Either of you feel like maintaining this module? I don't use it anymore. I can update you on the list if so.

**Comment by alanmels** [comment]
We will be actively using BuEditor on couple of projects, so I am interested in taking over the project. Thanks!

**Comment by herbdool** [comment]
Ok, I'll add your name. Thanks @alanmels !

**Comment by herbdool** [comment]
Done

**Comment by alanmels** [comment]
Thanks @herbdool!

@findlabnet, Vladimir, would you like to offer PR?

**Comment by findlabnet** [comment]
@alanmels, Alan, sure - today later.

**Comment by findlabnet** [comment]
PR: https://github.com/backdrop-contrib/bueditor/pull/11

**Comment by alanmels** [comment]
PR is merged, thanks a lot!
