### ISSUE TITLE
BU editor shows on plain text fields

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/bueditor#18]
**Steps to reproduce**

1. Install BU editor on site
2. Check that plain text 'text editor' setting is set to None
3. Add a text field (either short or long) to a content type with Text area widget and set Text processing to Plain text rather than Filtered text
4. Create new content with the content type

**Expected result** :  field has plain text area box
![image](https://user-images.githubusercontent.com/20357797/183453555-43227af8-1da5-4dd5-8830-87da470a7e4c.png)

**Actual result** : field has BU editor text area box
![image](https://user-images.githubusercontent.com/20357797/183453816-6bdf441f-36d7-4bf9-826f-269aa7974e94.png)

There is a comparable D7 issue - https://www.drupal.org/project/bueditor/issues/1931862 and there is a patch.  However, the function and variables looks quite different in that function in the Backdrop module so I'm not sure if it can be used directly:

<details>

```
diff --git a/bueditor.inc b/bueditor.inc
index d4af194..66899df 100644
--- a/bueditor.inc
+++ b/bueditor.inc
@@ -81,6 +81,17 @@ function _bueditor_textarea($element, $form_state) {
   }
   $textareas[$element['#id']] = TRUE;
 
+  // Check if this field instance has text processing enabled (filtered text
+  // with text format selection).
+  if (isset($element['#entity_type']) && isset($element['#field_name']) && $element['#bundle']) {
+    $instance = field_info_instance($element['#entity_type'], $element['#field_name'], $element['#bundle']);
+    // If text processing is 0 (plain text), don't show the editor for this
+    // textarea (plain text format doesn't allow any html).
+    if (!empty($instance) && empty($instance['settings']['text_processing'])) {
+      return $element;
+    }
+  }
+
   // Get editors
   if (!isset($editors)) {
     $editors = bueditor_user_eids($GLOBALS['user']);
```

</details>

**Comment by alanmels** [comment]
Sorry to get to this only now. Have you tried to apply the patch on DO?
