### ISSUE TITLE
Convert bueditor tables into config

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/bueditor#3]
Bueditor stores editors and buttons in tables and has it's own unique way of exporting and importing them. I wonder how much trouble it would be to convert those to use config?

**Comment by docwilmot** [comment]
Sounds like an idea but from the size of the data you'd be storing alone I'd guess tables would be best: For buttons alone, there are 18 buttons in total, 7 fields per button, and up to fifteen lines of text per button content field. How would you approach this?

**Comment by klonos** [comment]
Yeah, fair enough about the performance and the size of the data, but on the other hand we are trying to convert everything to CMI so that developers can use modern methods of deploying stage to live.

**Comment by herbdool** [comment]
Perhaps an approach would be one file per editor, much like there is a separate file for each field instance with the content types.

**Comment by herbdool** [comment]
I've put a bunch of work into this. This module is a bit byzantine and turning tables into config requires a different approach. Still I've managed to get it to work and I've got a branch where each editor is a separate config file with its own settings and list of buttons. Pretty much everything is working ok; well enough to show everyone.

What do you think would work best? Push my branch up to this repo so you can test it?

One feature that would be an improvement would be to have each editor have a machine name instead of a number, much like it's done with fields and content types in CMI. But that can wait.

**Comment by docwilmot** [comment]
@herbdool I've ported way more modules than I could maintain, so if you'd like to take over this one, I would really appreciate it; just jump in and add your name as maintainer.
Otherwise, pushing the branch sounds like a good idea to me.

**Comment by herbdool** [comment]
I'll push a branch either way. I'm not sure about being a maintainer since I'm not familiar with most of the js code but I'm happy to contribute and consider being a maintainer. I'd also like to see if the original author ufku will be joining as a maintainer; looks like he's [considering](https://www.drupal.org/node/2412601).

The full change to CMI will break other modules that rely on bueditor -- the editors are now in CMI with machine names, etc., so I'm thinking this would be a 1.x-2.x branch. 

I've also been working on incorporating the icons from markdowneditor. They are definitely nicer than the dated bueditor icons. And while I'm doing that it was only a tiny step to just include the markdowneditor library and buttons. If BUEditor is going to include bbcode, it could also include markdown as one of the defaults. So that could also go into a 1.x-2.x branch.

**Comment by herbdool** [comment]
1.x-2.x branch is now up https://github.com/backdrop-contrib/bueditor/tree/1.x-2.x
