### ISSUE TITLE
 Visibility of the Bueditor buttons - strange behavior and strange solution

### ISSUE THREAD

**Issue by amilenkov** [backdrop-contrib/bueditor#9]
I installed bueditor-1.x-2.1 to backdrop-1.2.2 and assign Default Editor to User 1. 

But when starring new or editing an existing page, Bueditor buttons were not shown in the Body text area, but they were visible in the Summary text area (If it was activated). 

Body text area showed only the buttons of CKEditor but not those of Bueditor. Summary text area showed only buttons of Bueditor, but not those of CKEditor.

I've tried different solutions – I have reinstalled,  deleted the cache, I tried all kinds of settings. 

Finally I created a new text input text format (named Coder) similar to the Full HTML - without any html restriction or filters. I just wanted to see if the problem would exist it with a new text format

It all started to work fine - both Bueditor and CKEditor become vissible at both Body and Summary text areas. In all text formats including default Filtered HTML and Full HTML.

After deleting newly created Coder text format both Bueditor and CKEditor buttons continue to work fine and now are visible in both Body and Summary text areas in Filtered HTML and Full HTML.

**Comment by herbdool** [comment]
I haven't tried this with the latest version where CKeditor is in core. I would probably not try to run them both, if you don't need both, since they have quite different ways of interacting with the body fields. BUeditor is pretty crusty, and the only reason I use it is so that I can use markdown.

**Comment by amilenkov** [comment]
Thanks for the information. You are right - the problem comes from CKeditor - if you deactivate CKeditor and the problem disappears. There is some incompatibility. 
But I've found it even easier solution to solve the problem. It is enough to change order of text formats. Deactivate the CKEditor for Full HTML and leave it active for Filtered HTML. Then move Full HTML at the top of the list of text formats, above Filtered HTML. The problem disappears.
